### ISSUE TITLE
Version 0.1.0 hosted on pub.dartlang.org has no SignInAuthResultSuccess

### ISSUE THREAD

**Issue by formatCvt** [wstrange/firebase_dart_ui#6]
Hi! Version 0.1.0 hosted on pub.dartlang.org has no SignInAuthResultSuccess callback. `auth_ui_js.dart` file seems to be outdated.

![screen shot 2018-08-31 at 21 29 11](https://user-images.githubusercontent.com/9342933/44929935-673aa980-ad65-11e8-9ea4-e30ae1ae6485.png)

**Comment by bgetsug** [comment]
workaround: add the following to `pubspec.yaml`:
```yaml
dependencies:
  #...
  firebase_dart_ui:
    git:
      url: https://github.com/wstrange/firebase_dart_ui
      ref: master
```

@wstrange Thanks for this...any ETA on publishing an update?
